### ISSUE TITLE
Landing

### ISSUE THREAD

**Issue by utkbansal** [Software-Incubator/silive.in#1]
The landing is very dull and the images used are of low quality. Get some better images.
Also the quote is Love.Peace.Code. not peace love code.

@shobhitagarwal1612  @shivangi14  @sukankshi @aditi23 @AnupKumarGupta @yadavankit comments?

**Comment by utkbansal** [comment]
@sukankshi @shivangi14 @shobhitagarwal1612 comments?

**Comment by sukankshi** [comment]
Place alumni above footer

**Comment by shivangi14** [comment]
Think some other way for client section. Compress it somehow.

**Comment by sukankshi** [comment]
SI logo is missing. Think of something other than animation for logo.
