### ISSUE TITLE
Scroll Up button behaviour and Color

### ISSUE THREAD

**Issue by yadavankit** [Software-Incubator/silive.in#10]
This Scroll Up button has nothing to do on the First section of the page.
Look into it and well, the color of the button doesn't match with any color used on the page.
![screen shot 2016-07-06 at 8 46 39 pm](https://cloud.githubusercontent.com/assets/8945824/16623952/7de5c0ca-43bd-11e6-832c-2e55de099b37.png)

**Comment by yadavankit** [comment]
@jaiyeshsidh don't keep that arrow in the button transparent. Fill it white.

**Comment by jaiyeshsidh** [comment]
Okay Sir.
I was thinking to put this Scroll top button in footer.
