### ISSUE TITLE
Client Section issue

### ISSUE THREAD

**Issue by shivangi14** [Software-Incubator/silive.in#6]
Think some other way for client section. Compress it somehow.

**Comment by yadavankit** [comment]
what I would recommend is using a slider for testimonials (displays one testimonial at a time, along with image of person) and a small slider below it displaying all our client logos. Whatsay @shivangi14 @shobhitagarwal1612 @animesh21 @jaiyeshsidh @utkbansal @sukankshi

**Comment by sukankshi** [comment]
Testimonials and clients are different. Testimonials is something given by dierector while clients are something like kuka, RDForge .Two sliders won't look good. Sliders can be shown in smaller screen. @shivangi14 @yadavankit

**Comment by yadavankit** [comment]
@sukankshi Not getting me. Gathering testimonials from our clients is a good way of displaying feedback of the services they received through us. Thats what should be done to make that section more appealing and moreover, have a look at any site, it makes the visitor trust the quality of service we provide

**Comment by yadavankit** [comment]
@sukankshi well, testimonials aren't only given by the director. Testimonial is just a way of testifying someone's work. How can the director single handedly testify our work for clients who themselves are using our services? It would be the best practise to testify our work by the clients themselves.

**Comment by sukankshi** [comment]
@yadavankit okay that we can do but can we place these mentors and clients testimonials together?
Suggest @shivangi14

**Comment by yadavankit** [comment]
@sukankshi yeah, that would be the best

**Comment by shivangi14** [comment]
Mentors have their description too along with their testimonials. Then how will you put the two together?

**Comment by yadavankit** [comment]
@shivangi14 that can be easily done
