### ISSUE TITLE
Floating close button on Portfolio-Modal 

### ISSUE THREAD

**Issue by yadavankit** [Software-Incubator/silive.in#9]
There is no need of two Close buttons on the Modal.
Delete them, make a new floating close button (preferably at the top right corner) that remains at the same position even on scrolling the portfolio.
![screen shot 2016-07-06 at 8 33 50 pm](https://cloud.githubusercontent.com/assets/8945824/16622929/84311cda-43b9-11e6-9bf1-10726ba5f1f8.png)

**Comment by jaiyeshsidh** [comment]
Sir now it has been Resolved
